[package]
name = "dipstick"
version = "0.7.0-alpha.0"
authors = ["Francis Lalonde <fralalonde@gmail.com>"]

description = """A fast and modular metrics library decoupling app instrumentation from reporting backend.
 Similar to popular logging frameworks, but with counters and timers.
 Can be configured for combined outputs (log + statsd), random sampling, local aggregation of metrics, recurrent background publication, etc."""

documentation = "https://docs.rs/dipstick"
homepage = "https://github.com/fralalonde/dipstick"
repository = "https://github.com/fralalonde/dipstick"
readme = "README.md"
keywords = ["metrics", "statsd", "graphite", "timer", "monitoring"]
license = "MIT/Apache-2.0"
build = "build.rs"

[badges]
travis-ci = { repository = "fralalonde/dipstick", branch = "master" }

[dependencies]
log = "0.4"
time = "0.1"
lazy_static = "1.0"
derivative = "1.0"
atomic_refcell = "0.1"
skeptic = { version = "0.13", optional = true }
num = { version = "0.1", default-features = false }

[build-dependencies]
skeptic = { version = "0.13", optional = true }

[features]
bench = []
# enables the use of the mock metric clock outside of dipstick's own tests
# this disables real-time metrics clock and should not be used outside of tests
mock_clock = []

[package.metadata.release]
#sign-commit = true
#upload-doc = true
pre-release-replacements = [
  {file="README.md", search="dipstick = \"[a-z0-9\\.-]+\"", replace="dipstick = \"{{version}}\""}
  ]